### PR TITLE
UPDATE: refactor flow submits

### PR DESCRIPTION
**Pull request by Argeric**
remove tx table;
remove address indexed table;
add filed id and tx_hash for flow_submit table;

- - -
This change is [Reviewable](https://reviewable.io/reviews/Conflux-Chain/neurahive-scan/2)

### CODE REVIEW

**Comment by wanliqun** [comment]
LGTM

**Review by boqiu — APPROVED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Conflux-Chain/neurahive-scan/2)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Argeric)

**Review by boqiu — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Conflux-Chain/neurahive-scan/2)* status: all files reviewed, 1 unresolved discussion (waiting on @Argeric)

___
*[`store/store_submit.go` line 13 at r1](https://reviewable.io/reviews/Conflux-Chain/neurahive-scan/2#-NdEFJmhAf-XwwZAEbJ0:-NdEFJmhAf-XwwZAEbJ1:b9uorld) ([raw file](https://github.com/Conflux-Chain/neurahive-scan/blob/bfe658a67de84baa05d0b696f9ddffcdc9db0445/store/store_submit.go#L13)):*
> ```Go
> type Submit struct {
> 	ID               uint64     `gorm:"primaryKey;index:idx_sender_bn_id,priority:3"`
> 	BlockNumber      uint64     `gorm:"not null;index:idx_bn;index:idx_sender_bn_id,priority:2"`
> ```

It seems that `blockNumber` is useless for index `idx_sender_bn_id`.

**Review by Argeric — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Conflux-Chain/neurahive-scan/2)* status: all files reviewed, 1 unresolved discussion (waiting on @boqiu)

___
*[`store/store_submit.go` line 13 at r1](https://reviewable.io/reviews/Conflux-Chain/neurahive-scan/2#-NdEFJmhAf-XwwZAEbJ0:-NdEH2Eq8Nv_tgQdhNZ2:b63olsc) ([raw file](https://github.com/Conflux-Chain/neurahive-scan/blob/bfe658a67de84baa05d0b696f9ddffcdc9db0445/store/store_submit.go#L13)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

It seems that `blockNumber` is useless for index `idx_sender_bn_id`.
</blockquote></details>

fix composite index idx_sender_id

**Review by boqiu — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Conflux-Chain/neurahive-scan/2)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Argeric)

**Pull request merged**
